### ISSUE TITLE
Papercrane?

### ISSUE THREAD

**Issue by TheDiamondYT1** [MrNoahz/MrNoahz.github.io#1]
Where is it!?

**Comment by TheDiamondYT1** [comment]
Bump

**Comment by NoahBres** [comment]
I have no idea

**Comment by TheDiamondYT1** [comment]
I have the css file and a little part of the html file but hardly any of it

**Comment by TheDiamondYT1** [comment]
Its fine tho im gonna make my own with Node.js

**Comment by NoahBres** [comment]
Good luck!
